
version: '3.7'
networks:
  default:
    external:
      name: nhlflasknetwork
services:
  db:
    restart: always
    image: nhlmariadb2
    ports:
      - "3306:3306"
    volumes:
      - type: bind # TODO -- Make this a volume mount for production
        source: /Users/jonathanolson/GitHub/NHL-Project
        target: /NHL-Project
      - type: volume
        source: mynhldb
        target: /var/lib/mysql
  web:
    restart: always
    image: ubuntuflask2
    ports:
      - "5000:5000"
    volumes:
      - type: bind # TODO -- Make this a volume mount for production
        source: /Users/jonathanolson/GitHub/NHL-Project
        target: /NHL-Project
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SECRET_KEY=$SECRET_KEY
    links:
      - db
    command: bash -c "pip3 install -r NHL-Project/newvenvRequirements.txt && python3 NHL-Project/flaskrun.py"
  server:
    image: nginx
    volumes:
      - type: bind # TODO -- Make this a volume mount for production
        source: /Users/jonathanolson/GitHub/NHL-Project/flasksite/templates
        target: /usr/share/nginx/html
      - type: bind # TODO -- Make this a volume mount for production
        source: /Users/jonathanolson/GitHub/NHL-Project/flasksite/static/favicon.ico
        target: /usr/share/nginx/html/favicon.ico
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  gunicornservice:
    image: mygunicorn
    volumes:
      - type: bind # TODO -- Make this a volume mount for production
        source: /Users/jonathanolson/GitHub/NHL-Project
        target: /NHL-Project
    working_dir: /NHL-Project
    command: /bin/sh -c "apk add py3-setuptools && pip3 install -r newvenvRequirements.txt && gunicorn -w 5 flaskrun:app"
volumes:
  mynhldb:
    external: true
